name: mad_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sembast: ^3.8.2
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.2.1
  permission_handler: ^10.0.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
